config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :messages, only: [:new, :index, :create]
  get '/thank_you' => 'static_pages#thank_you'
  get '/my-messages' => 'static_pages#my_messages', as: :my_messages
  root to: 'static_pages#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id, counter_cache: :messages_sent_count
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id, counter_cache: :messages_received_count
  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  validates :body, presence: true
  validates_associated :sender
  validates_associated :receiver
  validate :sender_is_not_receiver
  validate :sender_has_messages_to_send
  validate :receiver_can_receive
  after_create :send_message_mailer, :decrement_sender_remaining_messages, :check_if_prize_hit
  after_commit :display_message, on: [:create]
  scope :today, -> {where('created_at >= ?', Time.now - 24.hours)}
  scope :get_by_user, -> (user_id) do
    includes(:sender, :receiver)
      .where("sender_id = ? OR receiver_id = ?", user_id, user_id)
      .map{|message| message.get_node_with_people}
  end
  scope :get_random, -> (number) do
    includes(:sender, :receiver)
      .order("RANDOM()")
      .last(number).map{|message| message.get_node_with_people}
  end
  WIN_PRIZE_AMOUNT = 3.freeze

  def get_node
    {id: self.id, label: self.body}
  end

  def get_node_with_people
    {
      id: self.id,
      label: self.body,
      sender: {
        id: self.sender.id,
        email: self.sender.email,
        messages_sent_count: self.sender.messages_sent_count
      },
      receiver: {
        id: self.receiver.id,
        email: self.receiver.email,
        messages_sent_count: self.sender.messages_sent_count
      }
    }
  end

  def thank_you_message
    if self.sender.has_messages_remaining?
      return <<-eos
        <p>
          You've got #{self.sender.messages_remaining} more messages to send this week!.
        </p>
        <p>
          <a data-remote=true href=\'/messages/new\'>
            Send Another?
          </a>
        </p>
      eos
    else
      '<p>That was your last message for this period, send more next week!</p>'
    end
  end

  def get_time_sent
    created_at.localtime.strftime('%A, %B %e %Y, %I:%M %p')
  end


  private
    def display_message
      MessageDisplayJob.perform_async(self.id)
    end
    def sender_is_not_receiver
      errors.add(:base, "You can't send messages to yourself, even though you definitely deserve them!") if receiver_id == sender_id
    end

    def sender_has_messages_to_send
      if sender.messages_remaining <= 0
        errors.add(:base, "You've already sent all of your messages for this period!")
      end
    end

    def receiver_can_receive
      unless receiver.messages_received_count < WIN_PRIZE_AMOUNT
        errors.add(:base, "They've already received a gift, spread the messages around!")
      end
    end

    def send_message_mailer
      #MessagesMailer.delay.message_received(self.id) unless Rails.env.development?
      true
    end

    def decrement_sender_remaining_messages
      sender = self.sender
      sender.update(messages_remaining: sender.messages_remaining - 1)
    end

    def check_if_prize_hit
      if self.receiver.messages_received_count === WIN_PRIZE_AMOUNT
        self.receiver.update(prize_hit: true, prize_hit_at: Time.now)
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages_received, class_name: 'Message', foreign_key: :receiver_id
  has_many :messages_sent, class_name: 'Message', foreign_key: :sender_id
  before_save :email_downcase
  after_create :set_messages
  scope :for_collection_select, ->(email) do
    where.not(email: email)
         .where('messages_received_count < ? ', Message::WIN_PRIZE_AMOUNT)
         .order(:email)
  end
  scope :prize_hit_today, -> {where("prize_hit_at >= ? ", Time.zone.now - 24.hours)}

  INITIAL_MESSAGE_AMOUNT = 3.freeze

  def has_messages_remaining?
    return true if messages_remaining > 0
    false
  end

  def messages
    Message.where("sender_id = ? OR receiver_id = ?", self.id, self.id)
  end

  def get_messages
    messages.map{|message| message.get_node_with_people}
  end

  def get_messages_with_random(number)
    user_messages = messages.map{|message| message.get_node_with_people}
    user_message_ids = user_messages.map{|v| v[:id]}
    random_messages = Message.get_random(number - user_message_ids.count)
                        .reject{|v| v if user_message_ids.include?(v[:id])}.compact
    user_messages + random_messages
  end

  private
  def set_messages
    self.messages_remaining = INITIAL_MESSAGE_AMOUNT
  end

  def email_downcase
    self.email = self.email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def set_user
    @user = User.find_by(email: get_cookie(:email_cookie))
    gon.user_id = @user.id if @user
  end
  def get_cookie(key)
    cookies.encrypted[key]
  end
  def set_cookie(key, value)
    cookies.encrypted[key] = value
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_user
  # POST /messages
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.js { render 'messages/create' }
        format.html { redirect_to thank_you_path, notice: "Thanks for sending #{@message.receiver.fname} a message!" }
      else
        format.js { render 'messages/errors' }
        format.html { render :'static_pages/index' }
      end
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:sender_id, :receiver_id, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @session = {}
    if get_cookie(:email_cookie)
      respond_to do |format|
        @session[:errors] = "You're already logged in. Logout if this isn't you!"
        format.js { render 'messages/new' }
        format.html { redirect_to root_path, notice: "You're already logged in. Logout if this isn't you!" }
      end
    else
      email = params[:session][:email].downcase
      respond_to do |format|
        if @user = User.find_by(email: email)
          set_cookie(:email_cookie,email)
          format.js { render 'sessions/create' }
          format.html { redirect_to root_path, notice: "You're logged in, send some messages" }
        else
          @session[:errors] = "You don't seem to be in our list, contact us if this is incorrect, and we'll add you ASAP!"
          format.js { render 'sessions/errors' }
          format.html { redirect_to root_path, notice: "You don't seem to be in our list, contact us if this is incorrect, and we'll add you ASAP!" }
        end
      end
    end
  end

  def destroy
    cookies.clear
    session.clear
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_user

  def index
    if @user
      gon.messages = @user.get_messages_with_random(150)
    else
      gon.messages = Message.get_random(150)
    end
    @message = Message.new
  end

  def my_messages
    unless @user
      flash[:notice] = "You can't view your messages unless you're signed in"
      return redirect_to root_path
    end
    gon.messages = @user.get_messages
    @message = Message.new
    render 'static_pages/index'
  end

  def thank_you
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Realtime D3 Messaging
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
  %body
    %nav.navbar.navbar-light.bg-faded
      %ul.nav.navbar-nav
        %li.nav-item.active
          %a.nav-link{:href => root_path}
            Xaxis messages
            %span.sr-only (current)
        -if @user
          %li.nav-item
            = link_to 'logout', logout_path, method: :delete, class: 'nav-link'

    .container-fluid
      = yield
    = Gon::Base.render_data({})
    = javascript_include_tag 'application'

app/views/messages/_errors.html.haml
- if message.errors.any?
  #error_explanation
    %ul
      - message.errors.full_messages.each do |msg|
        %li= msg

app/views/messages/_form.html.haml
.message-form
  %p Welcome #{@user.fname},
  -if @user.messages_remaining > 0
    %p
      Everyone plays a role in making Xaxis great again. Tell your coworkers how much you appreciate them, and why, by sending them a message. When they receive #{Message::WIN_PRIZE_AMOUNT}, they'll get a gift!
    %p
      Prizes range from a dirty napkin to a brand new car!
    = form_for @message||=Message.new, remote: true do |f|
      #errors
        = render partial: 'messages/errors', locals: {message: @message}
      .field
        = f.label :sender
        %br/
        - user ||= @user
        = user.email
        = f.hidden_field :sender_id, value: user.id
      .field
        = f.label :receiver
        %br/
        = f.collection_select :receiver_id, User.for_collection_select(user.email), :id, :email, {include_blank: ''}, {class: 'select2 form-control', width: '100%'}
      .field
        = f.label :body
        = f.text_area :body, rows: 10, cols: 10, class: 'form-control'
      .field
        = f.submit :'Send messages', class: 'btn btn-primary'
  -else
    %p
      You've already sent all of your messages, but don't worry they'll refill soon!
  %p
    = link_to 'My messages', my_messages_path, class: 'btn btn-primary'

app/views/messages/create.js.erb
$('form').parent().html("<%= j render(partial: 'static_pages/thank_you') %>");

app/views/messages/errors.js.erb
$('form #errors').hide().html("<%= j render partial: 'messages/errors', locals: {message: @message} %>").fadeIn(500);

app/views/messages/new.js.erb
$('.put-the-form').html("<%=  j render partial: 'messages/form', locals: {message: Message.new, user: @user} %>");
$( ".select2" ).select2({});

app/views/static_pages/_thank_you.html.haml
%p
  = @message.sender.fname << ','
  Thanks for sending a message to
  = @message.receiver.fname << ','
  we're sure (s)he's going to love it!
%p
  = @message.thank_you_message.html_safe

app/views/static_pages/index.html.haml
.row
  .col-sm-9.push-sm-3
    .row
      #message
    .row
      .col-sm-12.svg-container
        %svg
  .col-sm-12.col-md-3.pull-md-9.col-xs-12.form-entry
    #config
    %h1 Send a message
    .put-the-form
      -if cookies.encrypted[:email_cookie]
        = render partial: 'messages/form'
      -else
        = render 'sessions/form'